language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

install:
  - composer install

script:
  - html_attribute_content/vendor/bin/parallel-lint --exclude html_attribute_content/vendor .

before_deploy:
  - rm -rf html_attribute_content/vendor
  - zip -r 'HTML Attribute Content' html_attribute_content

deploy:
  provider: releases
  api_key:
    secure: fuLGULBdOuuFKh6kp+bfsxKCZU/MpWcW/dOdkbHehJ48XlSH+wIXp7bvwjsTiM66EFE4vKNkELOCunZ6UhnjhuCqq4EXlBsQ2U0k7SyB/MmF9QgdH+7fU7JD3FOmHc4cqeR6ETklbA2l+Un4Kvh0AkAL5j084P7xgwnOlXUi538=
  file: "HTML Attribute Content.zip"
  skip_cleanup: true
  on:
    php: 7.1
    tags: true
    condition: $TRAVIS_PULL_REQUEST = false
    repo: expressionengine-add-ons/HTML-Attribute-Content
